KOGITO-1184 : Kogito Quick Starts Scripts / User Tasks Update
kiegroup/kogito-quickstarts pull request #8
Opened 2020-02-13 21:05 UTC by inodeman

Hi @romartin @domhanak can you review this PR?

2020-02-13 22:47 UTC, romartin commented
@ederign @porcelli how is the owner for this? I cannot assign reviewers neither..

2020-03-04 15:57 UTC, evacchi requested changes
firstLineApprovalUserTaskAssignments and secondLineApprovalUserTaskAssignments show the workbench frame, this may be confusing for people using VSCode or other extensions; better cropping the image or redo the screenshot

2020-03-04 21:31 UTC, inodeman commented
Hi @evacchi fixed :-)

2020-03-05 10:38 UTC, evacchi approved these changes

2020-03-05 16:04 UTC, radtriste requested changes
Some changes to the doc

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
> +* Diagram Properties
`Diagram Properties (top)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
> +* Diagram Properties
`Diagram Properties (imports)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
> +* Diagram Properties
should be under `Diagram Properties (bottom)` to be in sync with other docs

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
> +* Diagram Properties
`Diagram Properties (bottom)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
> +<p align="center"><img src="docs/images/diagramProperties2.png"></p>
No imports for now in bpmn ...

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
> +* First Line Approval
`First Line Approval (top)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
> +<p align="center"><img src="docs/images/firstLineApprovalUserTask.png"></p>
please show only the properties panel to be in sync with other screenshots

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
> +* First Line Approval
`First Line Approval (bottom)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
> +* First Line Approval
`First Line Approval (Assignments)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
> +* Second Line Approval
`Second Line Approval (Assignments)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
(line 53) [prerequisites] with quarkus 1.3.0.*, we need GraalVM 19.3.1 minimum

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
(line 55) [prerequisites] GraalVM native image needs as well native-image extension: https://www.graalvm.org/docs/reference-manual/native-image/

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
(line 81) swagger-ui is only accessible in dev mode (so with mvn clean package quarkus:dev)
See https://quarkus.io/guides/openapi-swaggerui#use-swagger-ui-for-development

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
> +<p align="center"><img src="docs/images/secondLineApprovalUserTaskAssignments.png"></p>
What does this screenshot means ?

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +* Diagram Properties
`Diagram Properties (bottom)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +* Diagram Properties
`Diagram Properties (imports)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +* Diagram Properties
should be under Diagram Properties (bottom) to be in sync with other docs

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +<p align="center"><img src="docs/images/diagramProperties2.png"></p>
No imports for now in bpmn ...

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +* Diagram Properties
`Diagram Properties (top)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +* First Line Approval
`First Line Approval (top)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +<p align="center"><img src="docs/images/firstLineApprovalUserTask.png"></p>
please show only the properties panel to be in sync with other screenshots

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +* First Line Approval
`First Line Approval (assignments)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +* First Line Approval
`First Line Approval (bottom)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +* Second Line Approval
`Second Line Approval (Assignments)`

2020-03-05 16:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +<p align="center"><img src="docs/images/secondLineApprovalUserTaskAssignments.png"></p>
What does this screenshot means ?

2020-03-05 18:27 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
> +* Diagram Properties
Done @radtriste

2020-03-05 18:27 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
> +* Diagram Properties
Done @radtriste

2020-03-05 18:27 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
> +* Diagram Properties
Done @radtriste

2020-03-05 18:27 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
> +* Diagram Properties
Done @radtriste

2020-03-05 18:27 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
> +<p align="center"><img src="docs/images/diagramProperties2.png"></p>
Done @radtriste

2020-03-05 18:27 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +<p align="center"><img src="docs/images/firstLineApprovalUserTask.png"></p>
Hi @radtriste can you elaborate?

2020-03-05 18:27 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +* First Line Approval
Done @radtriste

2020-03-05 18:27 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +* First Line Approval
Done @radtriste

2020-03-05 18:28 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +* Second Line Approval
Done @radtriste

2020-03-05 18:28 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +<p align="center"><img src="docs/images/secondLineApprovalUserTaskAssignments.png"></p>
Hi @radtriste it is the assignments for the Second Line approval

2020-03-05 18:33 UTC, inodeman commented
Hi @radtriste can you re-review with the changes applied?

2020-03-06 09:04 UTC, radtriste requested changes
Minor changes

2020-03-06 09:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
as we are already using 1.3.0.Alpha2 in master, you can directly set 

`GraalVM 19.3+ installed`

2020-03-06 09:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
You can remove the `[prerequisites]`
I added it at the beginning to mention where the modification was but the line number was in fact more relevant.
Also, I would put the `GraalVM native image needs as well native-image extension [...]` before `Note that GraalVM native image compilation typically requires other packages[...]`

2020-03-06 09:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
add
`(Dev Mode Only) https://quarkus.io/guides/openapi-swaggerui#use-swagger-ui-for-development`

2020-03-06 09:04 UTC, radtriste commented on kogito-usertasks-quarkus/README.md
> +<p align="center"><img src="docs/images/secondLineApprovalUserTaskAssignments.png"></p>
I think you can remove this

2020-03-06 09:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +<p align="center"><img src="docs/images/firstLineApprovalUserTask.png"></p>
I think you can let it like that. does not hurt to know on which element we are. As long as it is readable

2020-03-06 09:04 UTC, radtriste commented on kogito-usertasks-springboot/README.md
> +<p align="center"><img src="docs/images/secondLineApprovalUserTaskAssignments.png"></p>
Why is it here ?
I think you can remove it from here.

2020-03-06 19:34 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
> +* First Line Approval
fixed @radtriste

2020-03-06 19:37 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
> +<p align="center"><img src="docs/images/firstLineApprovalUserTask.png"></p>
fixed @radtriste

2020-03-06 19:38 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
> +* First Line Approval
fixed @radtriste

2020-03-06 19:38 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
> +* First Line Approval
fixed @radtriste

2020-03-06 19:38 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
> +* Second Line Approval
fixed @radtriste

2020-03-06 19:39 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
fixed @radtriste

2020-03-06 19:39 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
fixed @radtriste

2020-03-06 19:40 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
fixed @radtriste

2020-03-06 20:27 UTC, inodeman commented on kogito-usertasks-quarkus/README.md
> +<p align="center"><img src="docs/images/secondLineApprovalUserTaskAssignments.png"></p>
fixed @radtriste

2020-03-06 20:27 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +* Diagram Properties
fixed @radtriste

2020-03-06 20:28 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +* Diagram Properties
fixed @radtriste

2020-03-06 20:28 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +* Diagram Properties
fixed @radtriste

2020-03-06 20:28 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +<p align="center"><img src="docs/images/diagramProperties2.png"></p>
fixed @radtriste

2020-03-06 20:28 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +* Diagram Properties
fixed @radtriste

2020-03-06 20:30 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +* First Line Approval
fixed @radtriste

2020-03-06 20:30 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +<p align="center"><img src="docs/images/firstLineApprovalUserTask.png"></p>
fixed @radtriste

2020-03-06 20:30 UTC, inodeman commented on kogito-usertasks-springboot/README.md
> +<p align="center"><img src="docs/images/secondLineApprovalUserTaskAssignments.png"></p>
fixed @radtriste

2020-03-06 20:32 UTC, inodeman commented
Hi @radtriste fixed, can you re-review?

2020-03-09 08:40 UTC, radtriste approved these changes
lgtm

2020-03-11 02:08 UTC, merged